### ISSUE TITLE
혹시 프로젝트 계속 하시나요? 

### ISSUE THREAD

**Issue by easylogic** [ChoDragon9/geometry#3]
저도 비슷한 프로젝트를 하고 있어서 관심이 가서 이슈 남겨봅니다.

**Comment by ChoDragon9** [comment]
@easylogic 
안녕하세요 :)
이 프로젝트는 잠깐 재미삼아 해본거라
지금 안하고 있습니다.

감사합니다.

**Comment by easylogic** [comment]
혹시나 다시 하시게 되면 같이 한번 해볼 수 있으면 좋겠네요. 
만드신 코드가 제가 생각해본 코드랑 많이 닮아 있어서 문의 드려봤습니다. 
답변 감사합니다. ^^
